### ISSUE TITLE
TODO LIST  Survive The Tempest

### ISSUE THREAD

**Issue by Jayllyz** [Jayllyz/SurvivetheTempest#1]
# TODO LIST :
- [ ] Update `rules` & `readme`
- [ ] Add achievements, example : finish the game 😆 
- [ ] Add personal best of the player 
- [ ] Fix difficulty
